# Generated by Django 3.1.1 on 2022-07-09 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.PositiveIntegerField(null=True)),
                ('area_of_specialization', models.CharField(choices=[('IT specialist', 'IT specialist'), ('Administative Assistant', 'Administrative Assistant'), ('Clerical And Data Entry Personel ', 'Clerical And Data Entry Personel'), ('Hospitality', 'Hospitality'), ('Customer Care', 'Customer Care'), ('Hospitality And Wait Staff', 'Hospitality And Wait Staff'), ('Nanny Services', 'Nanny Services')], max_length=100, null=True)),
                ('brief_info', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Location Address')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Mobile Phone Number')),
                ('current_location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('kisumu', 'kisumu'), ('Uasingishu', 'Uasin-gishu'), ('kwale', 'kwale')], max_length=20)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(default='empty.jpg', null=True, upload_to='images/', verbose_name='Profile picture')),
                ('profile_updated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
