# Generated by Django 3.1.1 on 2022-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='area_of_specialization',
            field=models.CharField(choices=[('IT specialist', 'IT specialist'), ('Administrative Assistant', 'Administrative Assistant'), ('Clerical And Data Entry Personel ', 'Clerical And Data Entry Personel'), ('Hospitality', 'Hospitality'), ('Customer Care', 'Customer Care'), ('Hospitality And Wait Staff', 'Hospitality And Wait Staff'), ('Nanny Services', 'Nanny Services')], max_length=100, null=True),
        ),
    ]
