# Generated by Django 3.2.9 on 2022-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='current_location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('kisumu', 'kisumu'), ('Uasin-gishu', 'Uasin-gishu'), ('kwale', 'kwale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='national_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='National Id'),
        ),
    ]
