# Generated by Django 3.1.1 on 2022-07-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='employer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='user_requesting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile'),
        ),
    ]
