# Generated by Django 3.1.1 on 2022-07-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20220709_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
