# Generated by Django 3.1.1 on 2022-07-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220711_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='terms_and_conditions',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='terms_and_conditions',
            field=models.BooleanField(null=True),
        ),
    ]
