# Generated by Django 3.1.1 on 2022-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20220711_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
