# Generated by Django 3.1.1 on 2022-07-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobrequest_area_of_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='area_of_specialization',
            new_name='profession_area',
        ),
    ]
