# Generated by Django 3.1.1 on 2022-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20220712_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='profession_area',
            new_name='area_of_specialization',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
