# Generated by Django 3.1.1 on 2022-07-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20220713_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findtalentrequest',
            old_name='contacts',
            new_name='phone_number',
        ),
    ]
