# Generated by Django 3.1.1 on 2022-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20220713_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='findtalentrequest',
            name='your_info',
            field=models.TextField(blank=True),
        ),
    ]
