# Generated by Django 3.1.1 on 2022-07-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_findtalentrequest_your_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findtalentrequest',
            old_name='email',
            new_name='user_email',
        ),
    ]
