# Generated by Django 3.1.1 on 2022-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20220713_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
